##Application Name
spring:
  application:
    name: "remessa"

##Connection Data-base
  datasource:
    url: jdbc:h2:mem:remessadb
    driver-class-name: org.h2.Driver
    username: sa
    password:

##H2 Configuration
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform:
    hibernate:
      ddl-auto: create-drop  #Drop Table
    show-sql: true           #Query sql views
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    com.inter.remessa: DEBUG
    org.hibernate.SQL: DEBUG
